---
- name: Install Wordpress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-server
  # user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
